apiVersion: v1
kind: ConfigMap
metadata:
  name: cyprus-config
  namespace: pms-platform
  labels:
    app: pms-platform
    component: cyprus-config
data:
  # Cyprus VAT Configuration
  CYPRUS_VAT_RATE: "0.09"
  TFA_API_URL: "https://www.tfa.mof.gov.cy/api"

  # Cyprus Police Registration
  CYPRUS_POLICE_API: "https://police.gov.cy/api"

  # SMS Providers URLs
  PRIMETEL_API_URL: "https://api.primetel.com.cy/sms/v1"
  PRIMETEL_SENDER_ID: "PMS"
  MTN_API_URL: "https://api.mtn.com.cy/sms/v1"
  MTN_SENDER_ID: "PMS"

  # JCC Payment Gateway
  JCC_API_URL: "https://api.jcc.com.cy/v2"

  # Localization Settings
  DEFAULT_LANGUAGE: "en"
  SUPPORTED_LANGUAGES: "el,en,he,ru"
  DEFAULT_CURRENCY: "EUR"
  SUPPORTED_CURRENCIES: "EUR,GBP,USD,ILS"
  TZ: "Asia/Nicosia"

  # Frontend URLs
  FRONTEND_URL: "https://admin.pms-cyprus.com"
  API_URL: "https://api.pms-cyprus.com"

---
apiVersion: v1
kind: Secret
metadata:
  name: cyprus-secrets
  namespace: pms-platform
  labels:
    app: pms-platform
    component: cyprus-secrets
type: Opaque
stringData:
  # JCC Payment Gateway Secrets
  JCC_MERCHANT_ID: "your_jcc_merchant_id_here"
  JCC_API_KEY: "your_jcc_api_key_here"

  # TFA (Tax For All) System
  TFA_API_KEY: "your_tfa_api_key_here"

  # Cyprus Police Registration
  CYPRUS_POLICE_API_KEY: "your_police_api_key_here"

  # SMS Provider Secrets
  PRIMETEL_API_KEY: "your_primetel_api_key_here"
  MTN_API_KEY: "your_mtn_api_key_here"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cyprus-localization
  namespace: pms-platform
  labels:
    app: pms-platform
    component: localization
data:
  # Greek translations (key features)
  greeting_el: "Καλώς ήρθατε"
  booking_confirmation_el: "Επιβεβαίωση κράτησης"
  check_in_el: "Άφιξη"
  check_out_el: "Αναχώρηση"
  payment_el: "Πληρωμή"

  # Hebrew translations (key features)
  greeting_he: "ברוכים הבאים"
  booking_confirmation_he: "אישור הזמנה"
  check_in_he: "צ'ק אין"
  check_out_he: "צ'ק אאוט"
  payment_he: "תשלום"

  # Russian translations (key features)
  greeting_ru: "Добро пожаловать"
  booking_confirmation_ru: "Подтверждение бронирования"
  check_in_ru: "Заселение"
  check_out_ru: "Выселение"
  payment_ru: "Оплата"

  # Date and time formats
  date_format_cyprus: "DD/MM/YYYY"
  time_format_cyprus: "HH:mm"
  datetime_format_cyprus: "DD/MM/YYYY HH:mm"

  # Currency formats
  currency_symbol_eur: "€"
  currency_symbol_gbp: "£"
  currency_symbol_usd: "$"
  currency_symbol_ils: "₪"

  # Phone number format
  phone_format_cyprus: "+357XXXXXXXX"

  # VAT display format
  vat_rate_display: "9%"
  vat_label_en: "VAT (9%)"
  vat_label_el: "ΦΠΑ (9%)"
  vat_label_he: "מע״מ (9%)"
  vat_label_ru: "НДС (9%)"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cyprus-business-rules
  namespace: pms-platform
  labels:
    app: pms-platform
    component: business-rules
data:
  # VAT Rules
  vat_accommodation_rate: "0.09"
  vat_reporting_frequency: "quarterly"
  vat_reporting_deadline_days: "30"  # 30 days after quarter end

  # Police Registration Rules
  police_registration_deadline_hours: "24"  # 24 hours after arrival
  police_registration_required_non_residents: "true"
  police_registration_required_long_stays_days: "3"  # > 3 days for residents

  # SMS Rules
  sms_cost_primetel_eur: "0.024"
  sms_cost_mtn_eur: "0.025"
  sms_max_length: "160"
  sms_retry_attempts: "3"
  sms_retry_delay_seconds: "30"

  # JCC Payment Rules
  jcc_supported_currencies: "EUR,GBP,USD,ILS"
  jcc_3ds_required: "true"
  jcc_settlement_delay_hours: "24"
  jcc_refund_window_days: "30"

  # Business Hours (Cyprus timezone)
  business_hours_start: "09:00"
  business_hours_end: "17:00"
  business_days: "monday,tuesday,wednesday,thursday,friday"

  # Compliance Thresholds
  compliance_score_excellent: "95"
  compliance_score_good: "85"
  compliance_score_needs_improvement: "70"

  # Alert Thresholds
  alert_overdue_registrations: "5"
  alert_failed_payments_percent: "10"
  alert_pending_vat_reports: "1"

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cyprus-vat-reminder
  namespace: pms-platform
  labels:
    app: pms-platform
    component: cyprus-automation
spec:
  schedule: "0 9 1 */3 *"  # 9 AM on 1st day of each quarter
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: vat-reminder
            image: curlimages/curl:latest
            command:
            - /bin/sh
            - -c
            - |
              echo "Sending VAT quarterly reminder..."
              curl -X POST http://pms-backend:5000/api/v1/cyprus/vat/quarterly-reminder \
                -H "Content-Type: application/json" \
                -d '{"action": "send_quarterly_reminder"}'
          restartPolicy: OnFailure

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cyprus-police-check
  namespace: pms-platform
  labels:
    app: pms-platform
    component: cyprus-automation
spec:
  schedule: "0 */6 * * *"  # Every 6 hours
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: police-check
            image: curlimages/curl:latest
            command:
            - /bin/sh
            - -c
            - |
              echo "Checking for overdue police registrations..."
              curl -X POST http://pms-backend:5000/api/v1/cyprus/police/check-overdue \
                -H "Content-Type: application/json" \
                -d '{"action": "check_overdue_registrations"}'
          restartPolicy: OnFailure