apiVersion: apps/v1
kind: Deployment
metadata:
  name: pms-gateway
  labels:
    app: pms-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pms-gateway
  template:
    metadata:
      labels:
        app: pms-gateway
    spec:
      containers:
      - name: gateway
        image: ghcr.io/cosmosorder/pms-gateway:latest
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8080"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: pms-gateway-service
spec:
  selector:
    app: pms-gateway
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer