# Docker Compose override for Cyprus-specific configuration
# Usage: docker-compose -f docker-compose.yml -f docker-compose.cyprus.yml up

version: '3.8'

services:
  pms-backend:
    environment:
      # Cyprus-specific environment variables
      - CYPRUS_FEATURES_ENABLED=true
      - DEFAULT_LANGUAGE=en
      - SUPPORTED_LANGUAGES=el,en,he,ru
      - DEFAULT_CURRENCY=EUR
      - SUPPORTED_CURRENCIES=EUR,GBP,USD,ILS
      - TZ=Asia/Nicosia

      # Cyprus VAT Configuration
      - CYPRUS_VAT_RATE=0.09
      - VAT_REPORTING_ENABLED=true
      - TFA_API_URL=https://www.tfa.mof.gov.cy/api

      # JCC Payment Gateway
      - JCC_ENABLED=true
      - JCC_API_URL=https://api.jcc.com.cy/v2
      - JCC_3DS_REQUIRED=true

      # Cyprus Police Registration
      - POLICE_REGISTRATION_ENABLED=true
      - POLICE_REGISTRATION_DEADLINE_HOURS=24
      - CYPRUS_POLICE_API=https://police.gov.cy/api

      # SMS Providers
      - SMS_ENABLED=true
      - SMS_DEFAULT_PROVIDER=PRIMETEL
      - PRIMETEL_API_URL=https://api.primetel.com.cy/sms/v1
      - PRIMETEL_SENDER_ID=PMS
      - MTN_API_URL=https://api.mtn.com.cy/sms/v1
      - MTN_SENDER_ID=PMS
    env_file:
      - .env.cyprus
    labels:
      - "cyprus.features.enabled=true"
      - "cyprus.vat.enabled=true"
      - "cyprus.police.enabled=true"
      - "cyprus.jcc.enabled=true"
      - "cyprus.sms.enabled=true"

  pms-admin:
    environment:
      # Cyprus admin configuration
      - NEXT_PUBLIC_CYPRUS_ENABLED=true
      - NEXT_PUBLIC_DEFAULT_LANGUAGE=en
      - NEXT_PUBLIC_SUPPORTED_LANGUAGES=el,en,he,ru
      - NEXT_PUBLIC_DEFAULT_CURRENCY=EUR
      - NEXT_PUBLIC_SUPPORTED_CURRENCIES=EUR,GBP,USD,ILS
      - NEXT_PUBLIC_VAT_RATE=0.09
      - NEXT_PUBLIC_JCC_ENABLED=true
      - NEXT_PUBLIC_HEBREW_RTL=true
      - TZ=Asia/Nicosia
    labels:
      - "cyprus.admin.enabled=true"
      - "cyprus.localization.enabled=true"

  pms-guest:
    environment:
      # Cyprus guest portal configuration
      - NEXT_PUBLIC_CYPRUS_ENABLED=true
      - NEXT_PUBLIC_DEFAULT_LANGUAGE=en
      - NEXT_PUBLIC_SUPPORTED_LANGUAGES=el,en,he,ru
      - NEXT_PUBLIC_JCC_PAYMENT=true
      - NEXT_PUBLIC_MULTI_CURRENCY=true
      - NEXT_PUBLIC_HEBREW_RTL=true
      - TZ=Asia/Nicosia
    labels:
      - "cyprus.guest.enabled=true"
      - "cyprus.payment.jcc=true"

  pms-staff:
    environment:
      # Cyprus staff app configuration
      - NEXT_PUBLIC_CYPRUS_ENABLED=true
      - NEXT_PUBLIC_DEFAULT_LANGUAGE=el
      - NEXT_PUBLIC_SUPPORTED_LANGUAGES=el,en
      - NEXT_PUBLIC_POLICE_REGISTRATION=true
      - NEXT_PUBLIC_SMS_ENABLED=true
      - TZ=Asia/Nicosia
    labels:
      - "cyprus.staff.enabled=true"
      - "cyprus.police.staff=true"

  pms-marketplace:
    environment:
      # Cyprus marketplace configuration
      - NEXT_PUBLIC_CYPRUS_ENABLED=true
      - NEXT_PUBLIC_DEFAULT_LANGUAGE=en
      - NEXT_PUBLIC_SUPPORTED_LANGUAGES=el,en,he,ru
      - NEXT_PUBLIC_LOCAL_MARKET=cyprus
      - TZ=Asia/Nicosia
    labels:
      - "cyprus.marketplace.enabled=true"

# Additional services for Cyprus
  cyprus-compliance-monitor:
    image: curlimages/curl:latest
    command: >
      sh -c "
        while true; do
          echo 'Checking Cyprus compliance...'
          curl -s http://pms-backend:5000/api/v1/cyprus/health || echo 'Cyprus services unavailable'
          sleep 3600  # Check every hour
        done
      "
    depends_on:
      - pms-backend
    labels:
      - "cyprus.monitoring.compliance=true"

  cyprus-vat-scheduler:
    image: alpine:latest
    command: >
      sh -c "
        echo 'Cyprus VAT scheduler started'
        # In production, this would run actual VAT report generation
        while true; do
          echo 'VAT report check...'
          sleep 86400  # Daily check
        done
      "
    labels:
      - "cyprus.vat.scheduler=true"

networks:
  default:
    driver: bridge
    labels:
      - "cyprus.network=true"

volumes:
  cyprus-data:
    driver: local
    labels:
      - "cyprus.storage=true"