apiVersion: apps/v1
kind: Deployment
metadata:
  name: pms-admin
  namespace: pms-frontend
  labels:
    app: pms-admin
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pms-admin
  template:
    metadata:
      labels:
        app: pms-admin
        version: v1
    spec:
      containers:
      - name: pms-admin
        image: localhost:5000/pms-admin:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            secretKeyRef:
              name: pms-secrets
              key: api-url
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: pms-secrets
              key: next-auth-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: pms-admin
  namespace: pms-frontend
  labels:
    app: pms-admin
spec:
  selector:
    app: pms-admin
  ports:
  - port: 3000
    targetPort: 3000
    name: http
  type: ClusterIP