# Development values for pms-backend
replicaCount: 1

image:
  repository: localhost:5000/pms-backend
  tag: latest
  pullPolicy: Always

env:
  NODE_ENV: development
  LOG_LEVEL: debug

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false