# Default values for pms-backend
replicaCount: 2

image:
  repository: localhost:5000/pms-backend
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5000

env:
  NODE_ENV: production
  PORT: 5000
  LOG_LEVEL: info

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

secrets:
  name: pms-secrets

healthcheck:
  liveness:
    path: /health
    port: 5000
    initialDelaySeconds: 30
    periodSeconds: 30
  readiness:
    path: /ready
    port: 5000
    initialDelaySeconds: 5
    periodSeconds: 5